// Landscape Builder. Copyright (c) 2016-2019 SCSM Pty Ltd. All rights reserved.

// For LBPerlinFractalNoise(..) that uses per-octave curve modifiers, see LBCSTopo.compute

// Returns the perlin fractal noise value at xPos, yPos
// Used in LBCSTopo for warping, LBCSGrass noise, LBCSTex noise
float LBPerlinFractalNoise(float xPos, float yPos, int octaves)
{
	// Input the position into the fractal noise function to get a value between 0 and 1
	// Fractal noise is generated by getting perlin noise output from world coordinate input
	// then adding scaled versions of itself to it
	float value = 0.0;
	int powInt = 1;
	for (int o = 0; o < octaves; o++)
	{
		//value += Value2D(float2(xPos * (float)powInt, yPos * (float)powInt)) / (float)(powInt * 2);

		// Get perlin, then normalise from input range of -1.0 to 1.0 by adding 1 and dividing by 2.
		value += ((Perlin2D(float2(xPos * (float)powInt, yPos * (float)powInt)) + 1.0) * 0.5) / (float)(powInt * 2) ;

		powInt *= 2;
	}
	return value;
}
